# Generated by Django 5.0.3 on 2024-03-15 03:20

import django.db.models.deletion
import index_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('HD', 'Is hidden')], default='PB', verbose_name='status')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'content"."comments',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('HD', 'Is hidden')], default='PB', verbose_name='status')),
                ('link', models.CharField(max_length=2048, verbose_name='link')),
                ('date_of_event', models.DateField(default=index_page.models.next_week_at_six_pm)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'content"."events',
            },
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('section_title', models.CharField(choices=[('CV', 'Block Cover'), ('PR', 'Block Performance'), ('ST', 'Block Statistics'), ('WA', 'Block Working Approach'), ('LS', 'Block List Of Services'), ('DC', 'Block Description of the Client'), ('QS', 'Block Questions'), ('CN', 'Block Contacts'), ('NN', '------')], default='NN', verbose_name='Section title')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'db_table': 'content"."index_content',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('HD', 'Is hidden')], default='PB', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'content"."posts',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('HD', 'Is hidden')], default='PB', verbose_name='status')),
                ('link', models.CharField(max_length=2048, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'content"."services',
            },
        ),
        migrations.CreateModel(
            name='DopFieldsIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('index_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_page.indexcontent')),
            ],
            options={
                'db_table': 'content"."dop_fields_index',
            },
        ),
    ]
