# Generated by Django 5.0.3 on 2024-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopfieldsindex',
            options={'verbose_name_plural': 'Additional fields'},
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dopfieldsindex',
            name='subtitle',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='subtitle'),
        ),
    ]
