# Generated by Django 5.0.3 on 2024-03-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_alter_dopfieldsindex_options_indexcontent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('HD', 'Is hidden')], default='PB', verbose_name='status')),
                ('link', models.CharField(max_length=1024, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'db_table': 'content"."forms',
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section_title',
            field=models.CharField(choices=[('PR', 'Block Performance'), ('ST', 'Block Statistics'), ('WA', 'Block Working Approach'), ('LS', 'Block List Of Services'), ('DC', 'Block Description of the Client'), ('CM', 'Block Comments'), ('QS', 'Block Questions'), ('CN', 'Block Contacts'), ('NN', '------')], default='NN', verbose_name='Section title'),
        ),
    ]
