# Generated by Django 5.0.3 on 2024-03-18 00:04

import index_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_forms_delete_comments_alter_indexcontent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('HD', 'Is hidden')], default='PB', verbose_name='status')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'content"."comments',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=256, verbose_name='mail')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'content"."subscribers',
            },
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_event',
            field=models.DateTimeField(default=index_page.models.next_week_at_six_pm),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='section_title',
            field=models.CharField(choices=[('CV', 'Block Cover'), ('PR', 'Block Performance'), ('ST', 'Block Statistics'), ('WA', 'Block Working Approach'), ('LS', 'Block List Of Services'), ('DC', 'Block Description of the Client'), ('QS', 'Block Questions'), ('CN', 'Block Contacts'), ('NN', '------')], default='NN', verbose_name='Section title'),
        ),
    ]
