# Generated by Django 5.0.2 on 2024-03-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0005_events_image_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='mail',
            field=models.CharField(max_length=256, unique=True, verbose_name='mail'),
        ),
    ]
